#95 closest parks filter operating coasters
captain-coaster/captain-coaster pull request #101
Opened 2024-01-06 00:22 UTC by richardcrete

2024-01-06 10:34 UTC, florian987 requested changes
should we limit the max number of results to smoething like 5? sometimes list is very long:

![image](https://github.com/captain-coaster/captain-coaster/assets/1555765/05a4971a-b2c3-4c5f-8cc7-ae2116df67d3)

2024-01-06 10:34 UTC, florian987 commented on translations/messages+intl-icu.fr.yaml
> +        noCloseParks: 'Aucun parc avec au moins un coaster ayant un score de minimum {score}% à moins de {distance} km de {name}'
to be removed

2024-01-06 14:50 UTC, richardcrete commented on translations/messages+intl-icu.fr.yaml
> +        noCloseParks: 'Aucun parc avec au moins un coaster ayant un score de minimum {score}% à moins de {distance} km de {name}'
Done, forgot to remove before commit

2024-01-06 14:53 UTC, richardcrete commented
> should we limit the max number of results to smoething like 5? sometimes list is very long:
> 
> ![image](https://private-user-images.githubusercontent.com/1555765/294667992-05a4971a-b2c3-4c5f-8cc7-ae2116df67d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTI5NTcsIm5iZiI6MTcwNDU1MjY1NywicGF0aCI6Ii8xNTU1NzY1LzI5NDY2Nzk5Mi0wNWE0OTcxYS1iMmMzLTRjNWYtOGNjNy1hZTIxMTZkZjY3ZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDZUMTQ1MDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNhZWQ3NWIzYjMzMzA0ZGE3MjJiY2MzMjY3MTAwNTQzNTlhNjljNjRlYjg4OTAyM2I0ODkzODdiZmIwYTlkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.veYPsxZlwwJvoaiMTHOSbixVYPdgMm2sZAU3EZbfAhQ)

@florian987 @shARPII how many parks shall we display in this section?

2024-01-07 10:05 UTC, florian987 commented
> @florian987 @shARPII how many parks shall we display in this section?

let's start with 5 to merge this quickly

2024-01-07 11:11 UTC, richardcrete commented
> > @florian987 @shARPII how many parks shall we display in this section?
> 
> let's start with 5 to merge this quickly

Done!

2024-01-07 11:18 UTC, florian987 approved these changes

2024-01-07 11:19 UTC, merged

2024-01-07 11:20 UTC, florian987 commented
thanks!