[#129] - Fix user's images counter with only enabled
captain-coaster/captain-coaster pull request #132
Opened 2024-09-25 18:07 UTC by richardcrete

2024-10-05 06:42 UTC, florian987 requested changes
please fix php cs fixer issues

2024-10-05 06:42 UTC, florian987 commented on src/Controller/UserController.php
> +                'images_counter' => $em->getRepository(Image::class)->countUserEnabledImages($user),
inject `ImageRepository` instead

2024-10-05 18:48 UTC, richardcrete commented on src/Controller/UserController.php
> +                'images_counter' => $em->getRepository(Image::class)->countUserEnabledImages($user),
Done!

2024-10-06 09:02 UTC, florian987 approved these changes

2024-10-06 09:03 UTC, merged